// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import { ThemeProvider } from '@/components/ThemeProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';


const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] });

export const metadata: Metadata = {
  title: 'AutoMint - Smart Invoice Revolution',
  description: 'Bridge Web2 and Web3 payments with AutoBills™. Create, manage, and pay smart invoices with crypto wallets and UPI support.',
  keywords: 'AutoMint, crypto payments, Web3, UPI, smart invoices, AutoBills, blockchain, cryptocurrency',
  authors: [{ name: 'AutoMint Team' }],
  openGraph: {
    title: 'AutoMint - Smart Invoice Revolution',
    description: 'Bridge Web2 and Web3 payments with AutoBills™',
    url: 'https://automint.app',
    siteName: 'AutoMint',
    images: [
      {
        url: 'https://automint.app/og-image.jpg',
        width: 1200,
        height: 630,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AutoMint - Smart Invoice Revolution',
    description: 'Bridge Web2 and Web3 payments with AutoBills™',
    images: ['https://automint.app/twitter-image.jpg'],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          themes={['light', 'dark']}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}